### PR TITLE
second move ..... ( you should also update npm )

### PR DESCRIPTION
**Pull request by ForsakenHarmony**

### CODE REVIEW

**Comment by coolaj86** [comment]
Updated. Thanks! :)

**Comment by ForsakenHarmony** [comment]
why didn't you keep it on github?

**Comment by coolaj86** [comment]
The practical reasons: Analytics, brand value, cross-promoting the next product I'm launching ( https://ppl.family ).

The philosophical reasons: I simply prefer solutions that are decentralized and open source.

I want free as in "free speech", not just free as in "free beer". GitHub is very, very political and they've shut down a number of open source projects on a whim and made up new rules later to justify it. However, it's not that I want to "boycott" them, but simply that I don't like personally using the 60+ million page views and downloads a month that could be used to support causes that I care about being used to support causes that either I don't care about or that I believe are being used simply to promote their brand and use more people's source code as marketing material for their business.

For people that believe the value-trade they're getting with GitHub is fair it's a great platform, but I'd rather build a community and relationship with people who code with me that's closer and that align with my personal values.

:)

**Comment by ForsakenHarmony** [comment]
Alright makes sense

**Pull request closed without merging**
